export enum ClassAlias {
  Brute = 'Brute',
  Tinkerer = 'Tinkerer',
  Spellweaver = 'Spellweaver',
  Scoundrel = 'Scoundrel',
  Cragheart = 'Cragheart',
  Mindthief = 'Mindthief',
  Sun = 'Sun',
  LightningBolts = 'Lightning Bolts',
  ThreeSpears = 'Three Spears',
  Circles = 'Circles',
  Eclipse = 'Eclipse',
  Cthulu = 'Cthulu',
  MusicNote = 'Music Note',
  AngryFace = 'Angry Face',
  Saw = 'Saw',
  Triangles = 'Triangles',
  TwoMinis = 'Two Minis',
}
